### ISSUE TITLE
Player persistence off

### ISSUE THREAD

**Issue by brokenhands** [brokenhands/A3M-PMC-Simulator#1]
Add wait for alive profile to init

**Comment by brokenhands** [comment]
More or less working, needs more testing for player persistence across resets.

**Comment by Fleshmachine** [comment]
more testing needed for saving player data from vehicles and other similar variations both with and without resets.

**Comment by brokenhands** [comment]
Any bugs outside of this are no longer mission related IMO. Closing for now
